compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  debug@*:
    dependencies:
      supports-color: "*"
  vite@*:
    dependencies:
      supports-color: "*"

  '@next/react-dev-overlay@*':
    peerDependencies:
      react: '*'

pnpFallbackMode: all

pnpMode: loose

yarnPath: .yarn/releases/yarn-4.3.1.cjs
