enableGlobalCache: true

packageExtensions:
  "@blueprintjs/table@*":
    peerDependencies:
      "@blueprintjs/icons": "*"
  "@next/react-dev-overlay@*":
    peerDependencies:
      react: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  vite@*:
    dependencies:
      ms: "*"
      supports-color: "*"

pnpFallbackMode: all

pnpMode: loose

yarnPath: .yarn/releases/yarn-4.12.0.cjs
