compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  debug@*:
    dependencies:
      supports-color: "*"
  vite@*:
    dependencies:
      supports-color: "*"

pnpFallbackMode: all

pnpMode: loose

yarnPath: .yarn/releases/yarn-4.5.1.cjs
