compressionLevel: mixed

enableGlobalCache: false

pnpFallbackMode: all

pnpMode: loose

yarnPath: .yarn/releases/yarn-4.2.2.cjs

packageExtensions:
  debug@*:
    dependencies:
      supports-color: "*"

  vite@*:
    dependencies:
      supports-color: "*"

  '@next/react-dev-overlay@*':
    peerDependencies:
      react: '*'
