compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@next/react-dev-overlay@*":
    peerDependencies:
      react: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  vite@*:
    dependencies:
      supports-color: "*"

pnpFallbackMode: all

pnpMode: loose

yarnPath: .yarn/releases/yarn-4.6.0.cjs
