FROM node:20 AS build

ARG VITE_MAPBOX_API_TOKEN
ENV VITE_MAPBOX_API_TOKEN=$VITE_MAPBOX_API_TOKEN

ARG VITE_MACROSTRAT_TILESERVER_V2
ENV VITE_MACROSTRAT_TILESERVER_V2=$VITE_MACROSTRAT_TILESERVER_V2

ARG VITE_MACROSTRAT_TILESERVER_V1
ENV VITE_MACROSTRAT_TILESERVER_V1=$VITE_MACROSTRAT_TILESERVER_V1

ARG VITE_MACROSTRAT_TILESERVER_DOMAIN
ENV VITE_MACROSTRAT_TILESERVER_DOMAIN=$VITE_MACROSTRAT_TILESERVER_DOMAIN

ARG VITE_MACROSTRAT_API_DOMAIN
ENV VITE_MACROSTRAT_API_DOMAIN=$VITE_MACROSTRAT_API_DOMAIN

ARG VITE_CORELLE_API_DOMAIN
ENV VITE_CORELLE_API_DOMAIN=$VITE_CORELLE_API_DOMAIN

ENV NODE_ENV=PRODUCTION

WORKDIR /usr/src/app
COPY . ./

RUN yarn cache clean
RUN yarn add
RUN yarn run bundle

CMD ["yarn", "run", "server"]
