#!/usr/bin/env bash

version=$(node -p "require('./package.json').version")

if [[ $(git diff --stat) != '' ]]; then
  echo 'Cannot deploy with uncommitted changes'
  exit 1
fi
echo 'Working directory is clean.'


echo "Tagging version v$version"

git tag -a "v${version}" -m "Version ${version}"

git push

echo "Deploying to strata"
deploy_dir=/data/projects/macrostrat/map

yarn run clean
export PUBLIC_URL=/map/
export NODE_ENV=production
export VITE_MACROSTRAT_TILESERVER_DOMAIN='https://tiles.macrostrat.org'
export VITE_MACROSTRAT_API_DOMAIN='https://macrostrat.org'

yarn run bundle

rsync -azv --delete dist/ strata:$deploy_dir/
