#!/usr/bin/env bash

if [[ $(git diff --stat) != '' ]]; then
  echo 'Cannot deploy with uncommited changes'
  exit 1
fi
echo 'Working directory is clean.'

version="$(node -p \"require('./package.json').version\")"

echo "Tagging version v$version"

git tag -a "v${version}" -m "Version ${version}"

git push

echo "Deploying to steno"
deploy_dir=/data/projects/macrostrat/map

npm run clean
export PUBLIC_URL=/map/
export NODE_ENV=production
npm run bundle

rsync -azv --delete dist/ steno:$deploy_dir/
